### PR TITLE
prepare scripts for Trio, this version for beta testers

### PR DESCRIPTION
**Pull request by marionbarker**
Add support for the nightscout Trio app.

### CODE REVIEW

**Comment by marionbarker** [comment]
For people who have access to the private repository, this can be tested now. Until the rename of the app is completed in the nightscout Trio dev branch, it will display the old name.

```
export SCRIPT_BRANCH=trio && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/$SCRIPT_BRANCH/TrioBuildSelectScript.sh)"
```

Once at least one clone is downloaded, the Trio customization select script can be used either from the prior script or directly:
```
export SCRIPT_BRANCH=trio && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/$SCRIPT_BRANCH/TrioCustomizationSelect.sh)"
```

**Comment by pheltzel** [comment]
This worked well for me, no issues. I kept seeing the same error when I was building (with the earlier script for 2.3 as well) and it appeared to clear up when I ran the maintenance scripts first. Might be worth considering adding those to the build instructions, for people updating or changing versions.

**Comment by MikePlante1** [comment]
✅ I ran the script to successfully download and build Trio to a phone. I then applied the `Change Default to Upload Dexcom Readings` customization via the script (looks to be the only option in the script as of now) and tested it on a phone by deleting and re-adding a G6 transmitter and it successfully defaulted upload readings to ON.

**Review by tmhastings — APPROVED** [review]
Verified the discord link is correct

**Review by MikePlante1 — APPROVED** [review]
Looks good to me to merge now.

**Pull request merged**
