### PR TITLE
Bring 'lightly tested' to a commit with IOS17 compatible widget

### PR DESCRIPTION
**Pull request by alisterburt**
This PR brings the lightly tested dev commit forwards a few weeks to LoopKit/LoopWorkspace@ca36d07 which has an ios17 compatible widget.

c.f.
https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Loop.20Status.20Widgets.20Issue/near/383988989

### CODE REVIEW

**Comment by marionbarker** [comment]
Thanks for the PR. I’ll update the SHA tomorrow and then close this PR. 

The change needs to be made to src/BuildLoopDev.sh and then build.sh is run to generate BuildLoopDev.sh. 

For more information-see the README file section for developers.

**Comment by alisterburt** [comment]
Makes sense, thanks for the info @marionbarker !

**Comment by marionbarker** [comment]
Close this PR. Replaced with PR #19 
Will test in dev branch then push to main.

**Comment by marionbarker** [comment]
Test in dev successful. (Got distracted - sorry it took so long to get back to this.)
Pushed to main.

**Comment by alisterburt** [comment]
Thanks @marionbarker - you're a star!

**Pull request closed without merging**
