### PR TITLE
update Trio discord link

### PR DESCRIPTION
**Pull request by marionbarker**

### CODE REVIEW

**Comment by tmhastings** [comment]
is this link from the official trio account?

**Comment by marionbarker** [comment]
This is one of a series of links I was given, and added to various commits for the script. Of the 4 links I found in history, this is the only one that works today.

**Comment by marionbarker** [comment]
@tmhastings and @MikePlante1 
Updated link again.

**Review by MikePlante1 — APPROVED** [review]
Checked link and it brought me to the welcome beta channel as expected.

**Pull request merged**
